### ISSUE TITLE
SEVERE: Exception sending context initialized event to listener instance of class mx.nic.rdap.server.listener.RdapInitializer

### ISSUE THREAD

**Issue by gclooi** [NICMx/rdap-server#114]
I have try Demo Server version 1.4.1, server errors appear. 

java -jar demo.jar 192.168.0.125 9999
Mar 16, 2021 4:18:06 PM org.apache.catalina.core.StandardContext setPath
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
Mar 16, 2021 4:18:06 PM org.apache.catalina.core.StandardContext setPath
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [rdap-server] does not meet these criteria and has been changed to [/rdap-server]
Mar 16, 2021 4:18:06 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-192.168.0.125-9999"]
Mar 16, 2021 4:18:06 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Mar 16, 2021 4:18:06 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Mar 16, 2021 4:18:06 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.36
Mar 16, 2021 4:18:06 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mar 16, 2021 4:18:07 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Shiro environment
Mar 16, 2021 4:18:08 PM mx.nic.rdap.db.service.DataAccessService loadImplementationFromProperties
INFO: The 'data-access-implementation' property is absent from the configuration. Falling back to explore the classpath.
Mar 16, 2021 4:18:08 PM mx.nic.rdap.db.service.DataAccessService loadImplementationFromClasspath
INFO: Found a data access implementation in the classpath: mx.nic.rdap.sql.impl.SqlProviderImplementation
Mar 16, 2021 4:18:08 PM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Attempting to find data source 'java:/comp/env/jdbc/rdap'...
Mar 16, 2021 4:18:08 PM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Data source not found. Attempting something else...
Mar 16, 2021 4:18:08 PM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Attempting to find data source 'java:comp/env/jdbc/rdap'...
Mar 16, 2021 4:18:08 PM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Data source not found. Attempting something else...
Mar 16, 2021 4:18:08 PM mx.nic.rdap.sql.DatabaseSession initRdapConnection
INFO: I could not find the RDAP data source in the context. This won't be a problem if I can find it in the configuration. Attempting that now...
Mar 16, 2021 4:18:08 PM mx.nic.rdap.sql.DatabaseSession testDatabase
INFO: Executing QUERY: select 1
Mar 16, 2021 4:18:08 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class mx.nic.rdap.server.listener.RdapInitializer
java.lang.IllegalArgumentException: java.lang.NullPointerException
        at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:84)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Unknown Source)
        at java.util.Properties.load0(Unknown Source)
        at java.util.Properties.load(Unknown Source)
        at mx.nic.rdap.sql.SQLProviderConfiguration.init(SQLProviderConfiguration.java:127)
        at mx.nic.rdap.sql.SQLProviderConfiguration.initForServer(SQLProviderConfiguration.java:86)
        at mx.nic.rdap.sql.SchemaConfiguration.init(SchemaConfiguration.java:34)
        at mx.nic.rdap.sql.impl.SqlProviderImplementation.init(SqlProviderImplementation.java:27)
        at mx.nic.rdap.db.service.DataAccessService.initialize(DataAccessService.java:43)
        at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:62)
        ... 9 more

Mar 16, 2021 4:18:08 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Mar 16, 2021 4:18:08 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
Mar 16, 2021 4:18:08 PM org.apache.catalina.core.ApplicationContext log
INFO: Cleaning up Shiro Environment
Mar 16, 2021 4:18:08 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-192.168.0.125-9999"]

**Comment by dhfelix** [comment]
Apparently, we did not test the demo on a Windows OS computer.

I have only been able to replicate the error on my Windows machine. In Ubuntu and Debian systems this error does not appear, and the demo works fine.

I will try to fix it, we are short in resources and I'm working in another project, Maybe i'll take me a few days to fix it.

**Comment by vincentbryanc** [comment]
@dhfelix, I've also tried it on our ubuntu server. This server error appears,

Oct 25, 2021 6:30:29 AM org.apache.catalina.core.StandardContext setPath
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
Oct 25, 2021 6:30:29 AM org.apache.catalina.core.StandardContext setPath
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [rdap-server] does not meet these criteria and has been changed to [/rdap-server]
Oct 25, 2021 6:30:30 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-127.0.0.5-9090"]
Oct 25, 2021 6:30:30 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Oct 25, 2021 6:30:30 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Oct 25, 2021 6:30:30 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.36
Oct 25, 2021 6:30:30 AM org.apache.catalina.loader.WebappLoader buildClassPath
INFO: Unknown loader jdk.internal.loader.ClassLoaders$AppClassLoader@8bcc55f class jdk.internal.loader.ClassLoaders$AppClassLoader
Oct 25, 2021 6:30:30 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 25, 2021 6:30:31 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Shiro environment
Oct 25, 2021 6:30:31 AM mx.nic.rdap.db.service.DataAccessService loadImplementationFromProperties
INFO: The 'data-access-implementation' property is absent from the configuration. Falling back to explore the classpath.
Oct 25, 2021 6:30:31 AM mx.nic.rdap.db.service.DataAccessService loadImplementationFromClasspath
INFO: Found a data access implementation in the classpath: mx.nic.rdap.sql.impl.SqlProviderImplementation
Oct 25, 2021 6:30:31 AM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Attempting to find data source 'java:/comp/env/jdbc/rdap'...
Oct 25, 2021 6:30:31 AM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Data source not found. Attempting something else...
Oct 25, 2021 6:30:31 AM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Attempting to find data source 'java:comp/env/jdbc/rdap'...
Oct 25, 2021 6:30:31 AM mx.nic.rdap.sql.DatabaseSession findRdapDataSource
INFO: Data source not found. Attempting something else...
Oct 25, 2021 6:30:31 AM mx.nic.rdap.sql.DatabaseSession initRdapConnection
INFO: I could not find the RDAP data source in the context. This won't be a problem if I can find it in the configuration. Attempting that now...
Oct 25, 2021 6:30:31 AM mx.nic.rdap.sql.DatabaseSession testDatabase
INFO: Executing QUERY: select 1
Oct 25, 2021 6:30:31 AM mx.nic.rdap.sql.SQLProviderConfiguration initForServer
INFO: Default SQL files will be loaded.
Oct 25, 2021 6:30:33 AM mx.nic.rdap.sql.model.CountryCodeModel loadAllFromDatabase
INFO: Loaded 247 country codes.
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.UserNotices init
INFO: Optional File 'tos.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/tos.xml
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.UserNotices init
INFO: Optional File 'notices.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/notices.xml
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.RequestNotices init
INFO: Optional File 'domain.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/domain.xml
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.RequestNotices init
INFO: Optional File 'entity.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/entity.xml
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.RequestNotices init
INFO: Optional File 'ns.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/ns.xml
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.RequestNotices init
INFO: Optional File 'autnum.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/autnum.xml
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.RequestNotices init
INFO: Optional File 'ip.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/ip.xml
Oct 25, 2021 6:30:33 AM mx.nic.rdap.server.notices.UserEvents init
INFO: Optional File 'events.xml' not found, continue.
        java.nio.file.NoSuchFileException: /WEB-INF/notices/events.xml
