### ISSUE TITLE
Severe error if "renderers" and "renderer.class" properties are not configured in renderers.properties

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#64]
If the "renderers" and "*.class" (for example, json.class) properties from renderers.properties file are commented or defined as empty, even if the default configuration is defined (for example "default = mx.nic.rdap.renderer.json.JsonRenderer"), the server throws the following stack trace when it tries to start:

16-Oct-2017 18:01:01.514 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class mx.nic.rdap.server.listener.RdapInitializer
 java.lang.IllegalArgumentException: java.lang.NullPointerException
        at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:67)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
...
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1853)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at mx.nic.rdap.server.renderer.RendererPool.loadRenderers(RendererPool.java:40)
        at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:52)
        ... 13 more

If renderers and renderer.class are required properties , it is necessary to include a comment in order to explain it and return a clear error message if they are missing

**Comment by dhfelix** [comment]
Comments were added to the renderers.properties file for the attributes to be configured.
Also a more precise error message is added when an exception is thrown caused by a bad configuration in the renderers.properties file.

**Comment by TheRedTrainer** [comment]
Verified. When "renderers", "renderer.class" or "renderer.main_mime" properties are missing in renderer.properties file, the exception is managed in a way that is easy to understand:

18-Oct-2017 15:29:44.879 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class mx.nic.rdap.server.listener.RdapInitializer
 java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: No 'json.class' value was provided in 'renderers.properties'.
...
Caused by: java.lang.IllegalArgumentException: No 'json.class' value was provided in 'renderers.properties'.
