### ISSUE TITLE
Entity roles configuration is case sensitive (should it be?)

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#66]
If an user tries to configure any of the owner_roles properties in configuration.properties (for example, owner_roles_domain) with a valid entity role "registrant" but using a different case (changing to upper case all the word or the first letter), the following error is displayed and the server cannot start:

17-Oct-2017 16:22:55.832 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class mx.nic.rdap.server.listener.RdapInitializer
 java.lang.IllegalArgumentException: mx.nic.rdap.db.exception.InitializationException: unknown role in property 'owner_roles_domain': Registrant
	at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:67)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1853)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: mx.nic.rdap.db.exception.InitializationException: unknown role in property 'owner_roles_domain': Registrant
	at mx.nic.rdap.server.configuration.RdapConfiguration.loadObjectOwnerRoles(RdapConfiguration.java:348)
	at mx.nic.rdap.server.configuration.RdapConfiguration.loadConfiguredOwnerRoles(RdapConfiguration.java:79)
	at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:57)
	... 13 more

Should the owner_roles configuration be case sensitive?

**Comment by pcarana** [comment]
Just to keep a simple answer: it shouldn't be case sensitive. The default behavior in similar configuration properties is to ignore the case.

This will be fixed.

**Comment by pcarana** [comment]
The main error was at the core, whenever a constant value (referencing to a RDAP catalog) was loaded from configuration using a function called "getByName" the string case was relevant; now it's irrelevant, since that function insted of use `String.equals(String)` now uses `String.equalsIgnoreCase(String)`.

Still with that fix, the server now loads the owner values in lowercase to keep the same behavior as in other configuration properties.

**Comment by TheRedTrainer** [comment]
Verified. The owner values are loaded in lowercase and the property is also validated ignoring the case.
