### ISSUE TITLE
Wrong error message is displayed when an allow_labels_mixture configuration error is logged

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#89]
If the admin configures an invalid value (for example "POTATO") for _allow_labels_mixture_ property in configuration.properties, the following message is display in server's log:

```
java.lang.IllegalArgumentException: mx.nic.rdap.db.exception.InitializationException: The following required properties were not found or are invalid values in configuration file : [is_country_code_released]
       at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:83)
       at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
       at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
       at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
       at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
       at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
       at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1852)
       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: mx.nic.rdap.db.exception.InitializationException: The following required properties were not found or are invalid values in configuration file : [is_country_code_released]
       at mx.nic.rdap.server.configuration.RdapConfiguration.loadRdapConfiguration(RdapConfiguration.java:330)
       at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:56)
       ... 13 more

```

**Comment by TheRedTrainer** [comment]
Verified. If the user configures an invalid ALLOW_LABELS_MIXTURE, the following error message is displayed on localhost log:

java.lang.IllegalArgumentException: mx.nic.rdap.db.exception.InitializationException: The following required properties were not found or are invalid values in configuration file : [allow_labels_mixture]
       at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:83)
       at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
       at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
       at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
       at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
       at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
       at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1852)
       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: mx.nic.rdap.db.exception.InitializationException: The following required properties were not found or are invalid values in configuration file : [allow_labels_mixture]
       at mx.nic.rdap.server.configuration.RdapConfiguration.loadRdapConfiguration(RdapConfiguration.java:330)
       at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:56)
       ... 13 more

29-Apr-2019 16:02:07.467 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Cleaning up Shiro Environment
